# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/21186/Desktop/test/BTFN/Genesys_riscv_10s.xdc

# IP: C:/Users/21186/Desktop/test/BTFN/BTB/ip/IROM/IROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IROM || ORIG_REF_NAME==IROM} -quiet] -quiet

# IP: C:/Users/21186/Desktop/test/BTFN/BTB/ip/pll_1/pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] -quiet

# XDC: c:/Users/21186/Desktop/test/digital_twin.gen/sources_1/ip/pll/pll_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/21186/Desktop/test/digital_twin.gen/sources_1/ip/pll/pll.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: c:/Users/21186/Desktop/test/digital_twin.gen/sources_1/ip/pll/pll_ooc.xdc
