set_property SRC_FILE_INFO {cfile:C:/Users/21186/Desktop/test/BTFN/Genesys_riscv_10s.xdc rfile:../../../../Genesys_riscv_10s.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1 export:INPUT save:INPUT read:READ} [current_design]
set_clock_groups -asynchronous -group [get_clocks clk_out1_pll] -group [get_clocks clk_out2_pll]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD11  IOSTANDARD LVDS     } [get_ports { i_sys_clk_n }]; #IO_L12N_T1_MRCC_33 Sch=sysclk_n
set_property src_info {type:XDC file:1 line:6 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD12  IOSTANDARD LVDS     } [get_ports { i_sys_clk_p }]; #IO_L12P_T1_MRCC_33 Sch=sysclk_p
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J23   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[30] }]; #IO_L1P_T0_AD0P_15 Sch=xadc0r_p
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K23   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[31] }]; #IO_L3P_T0_DQS_AD1P_15 Sch=xadc1r_p
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L22   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[35] }]; #IO_L2P_T0_AD8P_15 Sch=xadc8r_p
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L21   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[34] }]; #IO_L4P_T0_AD9P_15 Sch=xadc9r_p
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J24   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[32] }]; #IO_L1N_T0_AD0N_15 Sch=xadc0r_n
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K24   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[37] }]; #IO_L3N_T0_DQS_AD1N_15 Sch=xadc1r_n
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L23   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[33] }]; #IO_L2N_T0_AD8N_15 Sch=xadc8r_n
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K21   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[36] }]; #IO_L4N_T0_AD9N_15 Sch=xadc9r_n
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U27   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[20] }]; #IO_L13P_T2_MRCC_14 Sch=ja_p[1]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U28   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[21] }]; #IO_L13N_T2_MRCC_14 Sch=ja_n[1]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T26   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[25] }]; #IO_L12P_T1_MRCC_14 Sch=ja_p[2]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T27   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[24] }]; #IO_L12N_T1_MRCC_14 Sch=ja_n[2]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T22   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[22] }]; #IO_L5P_T0_D06_14 Sch=ja_p[3]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T23   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[27] }]; #IO_L5N_T0_D07_14 Sch=ja_n[3]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T20   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[23] }]; #IO_L4P_T0_D04_14 Sch=ja_p[4]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T21   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[26] }]; #IO_L4N_T0_D05_14 Sch=ja_n[4]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AC26  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[10] }]; #IO_L19P_T3_13 Sch=jc[1]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AJ27  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[11] }]; #IO_L20P_T3_13 Sch=jc[2]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AH30  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[15] }]; #IO_L18N_T2_13 Sch=jc[3]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AK29  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[14] }]; #IO_L15P_T2_DQS_13 Sch=jc[4]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AD26  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[12] }]; #IO_L19N_T3_VREF_13 Sch=jc[7]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AG30  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[17] }]; #IO_L18P_T2_13 Sch=jc[8]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AK30  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[13] }]; #IO_L15N_T2_DQS_13 Sch=jc[9]
set_property src_info {type:XDC file:1 line:37 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN AK28  IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[16] }]; #IO_L20N_T3_13 Sch=jc[10]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V27   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[0] }]; #IO_L16N_T2_A15_D31_14 Sch=jd[1]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y30   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[1] }]; #IO_L8P_T1_13 Sch=jd[2]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V24   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[5] }]; #IO_L23N_T3_A02_D18_14 Sch=jd[3]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W22   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[4] }]; #IO_L24N_T3_A00_D16_14 Sch=jd[4]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U24   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[2] }]; #IO_L23P_T3_A03_D19_14 Sch=jd[7]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN Y26   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[7] }]; #IO_L1P_T0_13 Sch=jd[8]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V22   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[3] }]; #IO_L22N_T3_A04_D20_14 Sch=jd[9]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W21   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[6] }]; #IO_L24P_T3_A01_D17_14 Sch=jd[10]
set_property src_info {type:XDC file:1 line:51 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V29   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[39] }]; #IO_L17P_T2_A14_D30_14 Sch=jb_p[1]
set_property src_info {type:XDC file:1 line:52 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V30   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[29] }]; #IO_L17N_T2_A13_D29_14 Sch=jb_n[1]
set_property src_info {type:XDC file:1 line:53 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V25   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[19] }]; #IO_L18P_T2_A12_D28_14 Sch=jb_p[2]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W26   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[9] }]; #IO_L18N_T2_A11_D27_14 Sch=jb_n[2]
set_property src_info {type:XDC file:1 line:55 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T25   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[38] }]; #IO_L14P_T2_SRCC_14 Sch=jb_p[3]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U25   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[28] }]; #IO_L14N_T2_SRCC_14 Sch=jb_n[3]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U22   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[18] }]; #IO_L21P_T3_DQS_14 Sch=jb_p[4]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U23   IOSTANDARD LVCMOS33 } [get_ports { virtual_seg[8] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=jb_n[4]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C26   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[2] }]; #IO_L11N_T1_SRCC_16 Sch=fmc_la_n[01]
set_property src_info {type:XDC file:1 line:64 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D26   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[3] }]; #IO_L11P_T1_SRCC_16 Sch=fmc_la_p[01]
set_property src_info {type:XDC file:1 line:65 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN G30   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[4] }]; #IO_L24N_T3_16 Sch=fmc_la_n[02]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H30   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[5] }]; #IO_L24P_T3_16 Sch=fmc_la_p[02]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E30   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[6] }]; #IO_L18N_T2_16 Sch=fmc_la_n[03]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E29   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[7] }]; #IO_L18P_T2_16 Sch=fmc_la_p[03]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H26   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[9] }]; #IO_L23P_T3_16 Sch=fmc_la_p[04]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A30   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[10] }]; #IO_L17N_T2_16 Sch=fmc_la_n[05]
set_property src_info {type:XDC file:1 line:72 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B30   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[11] }]; #IO_L17P_T2_16 Sch=fmc_la_p[05]
set_property src_info {type:XDC file:1 line:73 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C30   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[12] }]; #IO_L16N_T2_16 Sch=fmc_la_n[06]
set_property src_info {type:XDC file:1 line:74 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D29   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[13] }]; #IO_L16P_T2_16 Sch=fmc_la_p[06]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E25   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[14] }]; #IO_L3N_T0_DQS_16 Sch=fmc_la_n[07]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F25   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[15] }]; #IO_L3P_T0_DQS_16 Sch=fmc_la_p[07]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B29   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[16] }]; #IO_L15N_T2_DQS_16 Sch=fmc_la_n[08]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A28   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[18] }]; #IO_L9N_T1_DQS_16 Sch=fmc_la_n[09]
set_property src_info {type:XDC file:1 line:80 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B28   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[19] }]; #IO_L9P_T1_DQS_16 Sch=fmc_la_p[09]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A27   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[20] }]; #IO_L7N_T1_16 Sch=fmc_la_n[10]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B27   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[21] }]; #IO_L7P_T1_16 Sch=fmc_la_p[10]
set_property src_info {type:XDC file:1 line:83 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A26   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[22] }]; #IO_L10N_T1_16 Sch=fmc_la_n[11]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A25   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[23] }]; #IO_L10P_T1_16 Sch=fmc_la_p[11]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN T28   IOSTANDARD LVCMOS33 } [get_ports { virtual_led[26] }]; #IO_L11N_T1_SRCC_14 Sch=led[0]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN F26   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[25] }]; #IO_L5P_T0_16 Sch=fmc_la_p[12]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W23   IOSTANDARD LVCMOS33 } [get_ports { virtual_led[28] }]; #IO_L20P_T3_A08_D24_14 Sch=led[7]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS33 } [get_ports { virtual_led[0] }]; #IO_L19P_T3_A10_D26_14 Sch=led[1]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U30   IOSTANDARD LVCMOS33 } [get_ports { virtual_led[1] }]; #IO_L15N_T2_DQS_DOUT_CSO_B_14 Sch=led[2]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U29   IOSTANDARD LVCMOS33 } [get_ports { virtual_led[8] }]; #IO_L15P_T2_DQS_RDWR_B_14 Sch=led[3]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V20   IOSTANDARD LVCMOS33 } [get_ports {virtual_led[17] }]; #IO_L19N_T3_A09_D25_VREF_14 Sch=led[4]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E24   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[27] }]; #IO_L4P_T0_16 Sch=fmc_la_p[13]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B24   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[24] }]; #IO_L8N_T1_16 Sch=fmc_la_n[14]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C24   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[29] }]; #IO_L8P_T1_16 Sch=fmc_la_p[14]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A23   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[30] }]; #IO_L1N_T0_16 Sch=fmc_la_n[15]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B23   IOSTANDARD LVCMOS12 } [get_ports { virtual_led[31] }]; #IO_L1P_T0_16 Sch=fmc_la_p[15]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN D23   IOSTANDARD LVCMOS12 } [get_ports  i_uart_rx ]; #IO_L2N_T0_16 Sch=fmc_la_n[16]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN E23   IOSTANDARD LVCMOS12 } [get_ports  o_uart_tx ]; #IO_L2P_T0_16 Sch=fmc_la_p[16]
