# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/21186/Desktop/verify/FPGA/Genesys_riscv.xdc

# IP: ip/DRAM/DRAM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==DRAM || ORIG_REF_NAME==DRAM} -quiet] -quiet

# IP: ip/pll_1/pll.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==pll || ORIG_REF_NAME==pll} -quiet] -quiet
