// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vstudent_top.h for the primary calling header

#ifndef VERILATED_VSTUDENT_TOP___024ROOT_H_
#define VERILATED_VSTUDENT_TOP___024ROOT_H_  // guard

#include "verilated.h"


class Vstudent_top__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vstudent_top___024root final {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        VL_IN8(w_cpu_clk,0,0);
        VL_IN8(w_clk_50Mhz,0,0);
        VL_IN8(w_clk_rst,0,0);
        VL_IN8(virtual_key,7,0);
        CData/*0:0*/ student_top__DOT__dmem_is_irom_r;
        CData/*0:0*/ student_top__DOT__dmem1_is_irom_r;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ex_redir;
        CData/*0:0*/ student_top__DOT__u_core__DOT__redirect;
        CData/*0:0*/ student_top__DOT__u_core__DOT__id_redirect;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mstall;
        CData/*0:0*/ student_top__DOT__u_core__DOT__btb_wr;
        CData/*0:0*/ student_top__DOT__u_core__DOT__btb_flush;
        CData/*0:0*/ student_top__DOT__u_core__DOT__bhit0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__bhit1;
        CData/*2:0*/ student_top__DOT__u_core__DOT__q_cnt;
        CData/*1:0*/ student_top__DOT__u_core__DOT__pops;
        CData/*2:0*/ student_top__DOT__u_core__DOT__cnt_after_pop;
        CData/*0:0*/ student_top__DOT__u_core__DOT__accept;
        CData/*0:0*/ student_top__DOT__u_core__DOT__idr_r;
        CData/*3:0*/ student_top__DOT__u_core__DOT__alu_op_0;
        CData/*1:0*/ student_top__DOT__u_core__DOT__alu_a_sel_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__alu_b_sel_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_branch_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_jal_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_jalr_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_fencei_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_write_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_0;
        CData/*1:0*/ student_top__DOT__u_core__DOT__wb_sel_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__uses_rs1_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__uses_rs2_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_muldiv_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_csr_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_ecall_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_mret_0;
        CData/*3:0*/ student_top__DOT__u_core__DOT__alu_op_1;
        CData/*1:0*/ student_top__DOT__u_core__DOT__alu_a_sel_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__alu_b_sel_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_branch_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_jal_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_jalr_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_fencei_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_write_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__uses_rs1_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__uses_rs2_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_muldiv_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_csr_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_ecall_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_mret_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ld_m_v;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ld_e1_v;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ld_m1_v;
        CData/*0:0*/ student_top__DOT__u_core__DOT__issue0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__i1_base_dram;
        CData/*0:0*/ student_top__DOT__u_core__DOT__i1_base_safe;
        CData/*0:0*/ student_top__DOT__u_core__DOT__btfn_taken_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__i0_cold_jmp;
        CData/*0:0*/ student_top__DOT__u_core__DOT__i0_sys;
        CData/*0:0*/ student_top__DOT__u_core__DOT__i0_ctrl;
        CData/*0:0*/ student_top__DOT__u_core__DOT__raw01;
        CData/*0:0*/ student_top__DOT__u_core__DOT__waw01;
    };
    struct {
        CData/*0:0*/ student_top__DOT__u_core__DOT__casc_st_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__issue1;
        CData/*2:0*/ student_top__DOT__u_core__DOT__ras_sp;
        CData/*3:0*/ student_top__DOT__u_core__DOT__ras_cnt;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ras_push;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ras_ret_0;
        CData/*7:0*/ student_top__DOT__u_core__DOT__ghr;
        CData/*7:0*/ student_top__DOT__u_core__DOT__pht_idx_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__dir_pred_0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__br_override;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ras_pop_r;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fsel_rs1_0;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fsel_rs2_0;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fsel_rs1_1;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fsel_rs2_1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__valid_e0;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_e0;
        CData/*3:0*/ student_top__DOT__u_core__DOT__alu_op_e0;
        CData/*1:0*/ student_top__DOT__u_core__DOT__alu_a_sel_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__alu_b_sel_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_branch_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_jal_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_jalr_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_fencei_e0;
        CData/*2:0*/ student_top__DOT__u_core__DOT__branch_op_e0;
        CData/*2:0*/ student_top__DOT__u_core__DOT__mem_funct3_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_write_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_e0;
        CData/*1:0*/ student_top__DOT__u_core__DOT__wb_sel_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_m_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__pred_taken_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_csr_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_ecall_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_mret_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__pred_jalr_e0;
        CData/*7:0*/ student_top__DOT__u_core__DOT__pht_idx_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__btfn_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__valid_e1;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_e1;
        CData/*3:0*/ student_top__DOT__u_core__DOT__alu_op_e1;
        CData/*1:0*/ student_top__DOT__u_core__DOT__alu_a_sel_e1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__alu_b_sel_e1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_e1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_e1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_write_e1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__casc_st_e1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_dram_e1;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fs_rs1_e0;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fs_rs2_e0;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fs_rs1_e1;
        CData/*5:0*/ student_top__DOT__u_core__DOT__fs_rs2_e1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__br_taken;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mispredict;
        CData/*0:0*/ student_top__DOT__u_core__DOT__csr_wr;
        CData/*0:0*/ student_top__DOT__u_core__DOT__trap_ex;
        CData/*0:0*/ student_top__DOT__u_core__DOT__upd_br_r;
        CData/*0:0*/ student_top__DOT__u_core__DOT__upd_jal_r;
        CData/*0:0*/ student_top__DOT__u_core__DOT__upd_taken_r;
        CData/*0:0*/ student_top__DOT__u_core__DOT__upd_ptaken_r;
        CData/*0:0*/ student_top__DOT__u_core__DOT__upd_btfn_r;
        CData/*7:0*/ student_top__DOT__u_core__DOT__upd_idx_r;
        CData/*6:0*/ student_top__DOT__u_core__DOT__upd_widx_r;
        CData/*6:0*/ student_top__DOT__u_core__DOT__upd_wtag_r;
    };
    struct {
        CData/*0:0*/ student_top__DOT__u_core__DOT__pht_agreed;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_div_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__m_started;
        CData/*0:0*/ student_top__DOT__u_core__DOT__md_done;
        CData/*0:0*/ student_top__DOT__u_core__DOT__md_start;
        CData/*0:0*/ student_top__DOT__u_core__DOT__is_mul_e0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mul_v_m0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mul_hi_m0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mul_v_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mul_hi_x0;
        CData/*3:0*/ student_top__DOT__u_core__DOT__wstrb;
        CData/*3:0*/ student_top__DOT__u_core__DOT__sf_v;
        CData/*1:0*/ student_top__DOT__u_core__DOT__sf_wp;
        CData/*0:0*/ student_top__DOT__u_core__DOT__sf_w0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__sf_kill_m;
        CData/*0:0*/ student_top__DOT__u_core__DOT__sf_cy2;
        CData/*0:0*/ student_top__DOT__u_core__DOT__sf_byp_w0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__sf_byp_w1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__sf_ld_hit;
        CData/*0:0*/ student_top__DOT__u_core__DOT__sf_hit_m;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l0_st_m1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l1_st_m1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l0_fill_v;
        CData/*7:0*/ student_top__DOT__u_core__DOT__l0_fill_tag;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l0_hit_m;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l0_hit1_m;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l0_fill_vd;
        CData/*7:0*/ student_top__DOT__u_core__DOT__l0_fill_tagd;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l1_fill_v;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l1_fill_vd;
        CData/*7:0*/ student_top__DOT__u_core__DOT__l1_fill_tag;
        CData/*7:0*/ student_top__DOT__u_core__DOT__l1_fill_tagd;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l0_dw_en;
        CData/*0:0*/ student_top__DOT__u_core__DOT__l0_tw_en;
        CData/*0:0*/ student_top__DOT__u_core__DOT__valid_m0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__valid_m1;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_m0;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_m1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_m0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_m0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_m1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_m1;
        CData/*2:0*/ student_top__DOT__u_core__DOT__mem_funct3_m0;
        CData/*3:0*/ student_top__DOT__u_core__DOT__dmem_wen_r;
        CData/*3:0*/ student_top__DOT__u_core__DOT__dmem1_wen_r;
        CData/*0:0*/ student_top__DOT__u_core__DOT__valid_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__valid_x1;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_x0;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_x1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_x1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__mem_read_x1;
        CData/*1:0*/ student_top__DOT__u_core__DOT__ld_rot_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ld_b_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ld_h_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ld_sgn_x0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__ld_sb0;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_w0;
        CData/*4:0*/ student_top__DOT__u_core__DOT__rd_w1;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_w0;
        CData/*0:0*/ student_top__DOT__u_core__DOT__rd_wen_w1;
        CData/*3:0*/ student_top__DOT__u_core__DOT__perf_probe2;
        CData/*7:0*/ student_top__DOT__u_core__DOT__perf_probe3;
    };
    struct {
        CData/*0:0*/ student_top__DOT__u_core__DOT__u_md__DOT__dovf;
        CData/*0:0*/ student_top__DOT__u_core__DOT__u_md__DOT__spec_r;
        CData/*5:0*/ student_top__DOT__u_core__DOT__u_md__DOT__div_cnt;
        CData/*0:0*/ student_top__DOT__u_core__DOT__u_md__DOT__div_busy;
        CData/*0:0*/ student_top__DOT__u_core__DOT__u_md__DOT__q_neg;
        CData/*0:0*/ student_top__DOT__u_core__DOT__u_md__DOT__r_neg;
        CData/*0:0*/ student_top__DOT__u_core__DOT__u_md__DOT__rem_sel;
        CData/*0:0*/ student_top__DOT__u_core__DOT__u_md__DOT__done_r;
        CData/*7:0*/ student_top__DOT__bridge_inst__DOT__key_meta;
        CData/*7:0*/ student_top__DOT__bridge_inst__DOT__key_sync;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_req_toggle_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_ack_meta_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_ack_sync_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_req_meta_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_req_sync_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_req_sync_d_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_ack_toggle_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__led_channel_idle_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_req_toggle_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_ack_meta_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_ack_sync_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_req_meta_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_req_sync_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_req_sync_d_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_ack_toggle_cnt;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__seg_channel_idle_cpu;
        CData/*7:0*/ student_top__DOT__bridge_inst__DOT____Vcellout__seg_driver__ans;
        CData/*3:0*/ student_top__DOT__bridge_inst__DOT____Vcellinp__Mem_DRAM__wea;
        CData/*4:0*/ student_top__DOT__bridge_inst__DOT__seg_driver__DOT__count;
        CData/*3:0*/ student_top__DOT__bridge_inst__DOT__seg_driver__DOT__digit1;
        CData/*3:0*/ student_top__DOT__bridge_inst__DOT__seg_driver__DOT__digit2;
        CData/*3:0*/ student_top__DOT__bridge_inst__DOT__seg_driver__DOT__digit3;
        CData/*3:0*/ student_top__DOT__bridge_inst__DOT__seg_driver__DOT__digit4;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__start_tgl_cpu;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__stop_tgl_cpu;
        CData/*1:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__start_tgl_cnt_sync;
        CData/*1:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__stop_tgl_cnt_sync;
        CData/*0:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__start_run;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_16;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_19;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_20;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_21;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_22;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_24;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_27;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_28;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_29;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_30;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_31;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_33;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_34;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_37;
        CData/*0:0*/ __VdfgRegularize_h6e95ff9d_0_42;
        CData/*0:0*/ __Vdly__student_top__DOT__bridge_inst__DOT__counter_inst__DOT__start_tgl_cpu;
        CData/*0:0*/ __Vdly__student_top__DOT__bridge_inst__DOT__counter_inst__DOT__stop_tgl_cpu;
        CData/*0:0*/ __Vdly__student_top__DOT__bridge_inst__DOT__led_ack_toggle_cnt;
        CData/*0:0*/ __Vdly__student_top__DOT__bridge_inst__DOT__seg_ack_toggle_cnt;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __VstlPhaseResult;
        CData/*0:0*/ __VicoFirstIteration;
        CData/*0:0*/ __VicoPhaseResult;
        CData/*0:0*/ __Vtrigprevexpr___TOP__w_cpu_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__w_clk_rst__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__w_clk_50Mhz__0;
    };
    struct {
        CData/*0:0*/ __VactPhaseResult;
        CData/*0:0*/ __VnbaPhaseResult;
        SData/*11:0*/ student_top__DOT____Vcellinp__u_irom__addr0;
        SData/*13:0*/ student_top__DOT__u_core__DOT__upd_wtgt_r;
        SData/*9:0*/ student_top__DOT__u_core__DOT__l0_fill_idx;
        SData/*9:0*/ student_top__DOT__u_core__DOT__l0_fill_idxd;
        SData/*9:0*/ student_top__DOT__u_core__DOT__l1_fill_idx;
        SData/*9:0*/ student_top__DOT__u_core__DOT__l1_fill_idxd;
        SData/*9:0*/ student_top__DOT__u_core__DOT__l0_dw_idx;
        SData/*15:0*/ student_top__DOT__u_core__DOT__perf_probe;
        SData/*15:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__cnt_1ms;
        VL_OUT(virtual_led,31,0);
        IData/*31:0*/ student_top__DOT__imem_rdata0;
        IData/*31:0*/ student_top__DOT__imem_rdata1;
        IData/*31:0*/ student_top__DOT__dmem_rdata;
        IData/*31:0*/ student_top__DOT__irom_drdata;
        IData/*31:0*/ student_top__DOT__irom_drdata1;
        IData/*31:0*/ student_top__DOT__dram_doutb;
        IData/*31:0*/ student_top__DOT__u_core__DOT__redirect_pc;
        IData/*31:0*/ student_top__DOT__u_core__DOT__pc_f;
        IData/*31:0*/ student_top__DOT__u_core__DOT__bi;
        IData/*31:0*/ student_top__DOT__u_core__DOT__pc_next;
        IData/*31:0*/ student_top__DOT__u_core__DOT__btgt0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__btgt1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__idr_pc_r;
        IData/*31:0*/ student_top__DOT__u_core__DOT__imm_0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__imm_1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs1_data_0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs2_data_0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs1_data_1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs2_data_1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__seg_dram_tbl;
        IData/*31:0*/ student_top__DOT__u_core__DOT__seg_flat_tbl;
        IData/*31:0*/ student_top__DOT__u_core__DOT__pc_e0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__instr_e0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__imm_e0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs1_data_e0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs2_data_e0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__pred_tgt_e0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__pc_e1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__instr_e1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__imm_e1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs1_data_e1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs2_data_e1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs1_fwd0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs2_fwd0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__rs2_fwd1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__alu_y0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__alu_a1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__alu_b1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__csr_mtvec;
        IData/*31:0*/ student_top__DOT__u_core__DOT__csr_mepc;
        IData/*31:0*/ student_top__DOT__u_core__DOT__csr_mcause;
        IData/*31:0*/ student_top__DOT__u_core__DOT__csr_mscratch;
        IData/*31:0*/ student_top__DOT__u_core__DOT__csr_rdata;
        IData/*31:0*/ student_top__DOT__u_core__DOT__csr_wval;
        IData/*31:0*/ student_top__DOT__u_core__DOT__br_tgt_e0;
        VlWide<3>/*65:0*/ student_top__DOT__u_core__DOT__mul_prod_x0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__agu_addr;
        IData/*31:0*/ student_top__DOT__u_core__DOT__wdata_sh;
        IData/*17:0*/ student_top__DOT__u_core__DOT__sf_waddr;
        IData/*31:0*/ student_top__DOT__u_core__DOT__sf_rdata_r;
        IData/*31:0*/ student_top__DOT__u_core__DOT__l0_spec_addr;
        IData/*31:0*/ student_top__DOT__u_core__DOT__l0_douta;
    };
    struct {
        IData/*31:0*/ student_top__DOT__u_core__DOT__agu_addr1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__l0_douta1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__l0_fill_data;
        IData/*31:0*/ student_top__DOT__u_core__DOT__l1_fill_data;
        IData/*31:0*/ student_top__DOT__u_core__DOT__l0_dw_data;
        IData/*31:0*/ student_top__DOT__u_core__DOT__alu_m0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__alu_m1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__dmem_addr_r;
        IData/*31:0*/ student_top__DOT__u_core__DOT__dmem_wdata_r;
        IData/*31:0*/ student_top__DOT__u_core__DOT__dmem1_addr_r;
        IData/*31:0*/ student_top__DOT__u_core__DOT__dmem1_wdata_r;
        IData/*31:0*/ student_top__DOT__u_core__DOT__alu_x0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__alu_x1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__ld_rot0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__load_data1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__result_w0;
        IData/*31:0*/ student_top__DOT__u_core__DOT__result_w1;
        IData/*31:0*/ student_top__DOT__u_core__DOT__u_md__DOT__spec_res_r;
        IData/*31:0*/ student_top__DOT__u_core__DOT__u_md__DOT__dividend;
        IData/*31:0*/ student_top__DOT__u_core__DOT__u_md__DOT__divisor;
        IData/*31:0*/ student_top__DOT__u_core__DOT__u_md__DOT__quot;
        IData/*31:0*/ student_top__DOT__u_core__DOT__u_md__DOT__quot_fin;
        IData/*31:0*/ student_top__DOT__u_core__DOT__u_md__DOT__rem_fin;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__LED_cpu;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__seg_wdata_cpu;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__LED_cnt;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__seg_wdata_cnt;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__cnt_rdata;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__dram_rdata;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__perip_addr_reg;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__led_tx_data_cpu;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__led_sent_value_cpu;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__seg_tx_data_cpu;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__seg_sent_value_cpu;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__cnt_ms;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__cnt_ms_gray_cpu_sync1;
        IData/*31:0*/ student_top__DOT__bridge_inst__DOT__counter_inst__DOT__cnt_ms_gray_cpu_sync2;
        IData/*31:0*/ __VactIterCount;
        VL_IN64(virtual_sw,63,0);
        VL_OUT64(virtual_seg,39,0);
        QData/*32:0*/ student_top__DOT__u_core__DOT__mul_a_m0;
        QData/*32:0*/ student_top__DOT__u_core__DOT__mul_b_m0;
        QData/*32:0*/ student_top__DOT__u_core__DOT__u_md__DOT__rem;
        QData/*32:0*/ student_top__DOT__u_core__DOT__u_md__DOT__sub;
        QData/*39:0*/ student_top__DOT__bridge_inst__DOT__seg_output_cnt;
        QData/*63:0*/ student_top__DOT__bridge_inst__DOT__sw_meta;
        QData/*63:0*/ student_top__DOT__bridge_inst__DOT__sw_sync;
        VlUnpacked<CData/*0:0*/, 128> student_top__DOT__u_core__DOT__btb_valid;
        VlUnpacked<CData/*6:0*/, 128> student_top__DOT__u_core__DOT__btb_tag;
        VlUnpacked<SData/*13:0*/, 128> student_top__DOT__u_core__DOT__btb_tgt;
        VlUnpacked<IData/*31:0*/, 4> student_top__DOT__u_core__DOT__q_pc;
        VlUnpacked<IData/*31:0*/, 4> student_top__DOT__u_core__DOT__q_instr;
        VlUnpacked<CData/*0:0*/, 4> student_top__DOT__u_core__DOT__q_pred;
        VlUnpacked<IData/*31:0*/, 8> student_top__DOT__u_core__DOT__ras;
        VlUnpacked<CData/*1:0*/, 256> student_top__DOT__u_core__DOT__pht;
        VlUnpacked<IData/*17:0*/, 4> student_top__DOT__u_core__DOT__sf_addr;
        VlUnpacked<IData/*31:0*/, 4> student_top__DOT__u_core__DOT__sf_data;
        VlUnpacked<IData/*31:0*/, 1024> student_top__DOT__u_core__DOT__l0_mem;
        VlUnpacked<CData/*7:0*/, 1024> student_top__DOT__u_core__DOT__l0_tag;
        VlUnpacked<CData/*0:0*/, 1024> student_top__DOT__u_core__DOT__l0_varr;
        VlUnpacked<IData/*31:0*/, 1024> student_top__DOT__u_core__DOT__l0_mem2;
        VlUnpacked<IData/*31:0*/, 32> student_top__DOT__u_core__DOT__u_rf__DOT__rfa;
        VlUnpacked<IData/*31:0*/, 32> student_top__DOT__u_core__DOT__u_rf__DOT__rfb;
        VlUnpacked<CData/*0:0*/, 32> student_top__DOT__u_core__DOT__u_rf__DOT__lvt;
    };
    struct {
        VlUnpacked<IData/*31:0*/, 4096> student_top__DOT__u_irom__DOT__rom_f;
        VlUnpacked<IData/*31:0*/, 4096> student_top__DOT__u_irom__DOT__rom_d;
        VlUnpacked<IData/*31:0*/, 65536> student_top__DOT__bridge_inst__DOT__Mem_DRAM__DOT__mem;
        VlUnpacked<QData/*63:0*/, 1> __VstlTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VicoTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VactTriggered;
        VlUnpacked<QData/*63:0*/, 1> __VnbaTriggered;
    };
    VlNBACommitQueue<VlUnpacked<CData/*0:0*/, 128>, false, CData/*0:0*/, 1> __VdlyCommitQueuestudent_top__DOT__u_core__DOT__btb_valid;

    // INTERNAL VARIABLES
    Vstudent_top__Syms* vlSymsp;
    const char* vlNamep;

    // CONSTRUCTORS
    Vstudent_top___024root(Vstudent_top__Syms* symsp, const char* namep);
    ~Vstudent_top___024root();
    VL_UNCOPYABLE(Vstudent_top___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
