# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/21186/Desktop/BTFN/BTB/constraint/Genesys_riscv.xdc

# IP: C:/Users/21186/Desktop/BTFN/BTB/ip/IROM/IROM.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==IROM || ORIG_REF_NAME==IROM} -quiet] -quiet
